config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  get 'login', to: 'user_sessions#new'   
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'
  resources :events   
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
    has_many :events, foreign_key: 'creator_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user  
    helper_method :loged_in?
    
    def current_user
      User.find_by(id: session[:user_id])  
    end

    def loged_in?
      !current_user.nil?
    end



  
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController


    def index
        @events = Event.all
    end



    def new
        @event = current_user.events.build()
    end

    def create
        @event = current_user.events.build(event_params)
        if @event.save
            redirect_to user_path(current_user)
        else 
            render :new
        end

    end

    def show
        @event = Event.find(params[:id])
    end

    private 
    def event_params
        params.require(:event).permit(:title, :event_date, :description, :location)
      end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
 def new
 end

 def create

    user = User.find_by_name(params[:name])
    if user
          session[:user_id] = user.id
          redirect_to root_url, notice: "Logged in!"
        else
          flash.now[:alert] = "Name is invalid"
          render "new"
        end
      
 end

def destroy
  session[:user_id] = nil
  redirect_to root_url, notice: "Loged out!"

end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
    @user = User.new
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            redirect_to user_path(@user)
        else 
            render action: :new
        end 
    end

    def show
        @user = User.find_by(params[:id])
       end

    def index
        @users = User.all
    end


    private
    def user_params
        params.require(:user).permit(:name)
       end

       
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/users_sessions_helper.rb
module UsersSessionsHelper
end

app/views/events/index.html.erb
<h1>All Events</h1>
<ul>
<% @events.each do |event| %>
    <li>
    <%= link_to event.title, event_path(event) %>
    </li>

<% end %>
</ul>

app/views/events/new.html.erb
<h1>Create New Event</h1>
<%= form_with model: @event do |f| %>
    <%= f.label :title %>
    <br>
    <%= f.text_field :title %>
    <br>
    <%= f.label :event_date %>
    <br>
    <%= f.date_select :event_date %>
    <br>
    <%= f.label :location %>
    <br>
    <%= f.text_field :location %>
    <br>
    <%= f.label :description %>
    <br>
    <%= f.text_area :description, placeholder: "Describe your event here...", cols: 40, rows: 20 %>
    <br>
    <%= f.submit "Create" %>
    <% end %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<small><%= @event.location %></small>
<small><%= @event.event_date %></small>
<br>
<br>
<div class="conatiner">
<p><%= @event.description %></p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p id=”notice”><%= notice %></p>
<% if loged_in? %>
  Logged in as <%= current_user.name %>
  <%= link_to "Logout", '/logout'%>
<% else %>
  <%= link_to "Login", '/login', method: :get%>
  <%= link_to "Sign Up", '/users/new', method: :get%>
 <% end %>

    <%= yield %>
  </body>
</html>

app/views/user_sessions/new.html.erb
<%= form_tag login_path, method: :post do %>
    <div class="field">
      <%= label_tag :name %></br>
      <%= text_field_tag :name %>
    </div>
    <div class="actions">
     <%= submit_tag "Login" %>
    </div>
  <% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Private Events</h1>


<h3>Chose Your Host:</h3>
<ul>
<% @users.each do |user| %>
  <li>
  <%= link_to user.name, user_path(user) %>
  </li>
<% end %>

</ul>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
    <%= f.text_field :name %>
    <%= f.submit :create %>
    <% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Events</h1>
<div>
<ul>
<% @user.events.all.each do |event| %>
    <li>
    <%= link_to event.title, event_path(event) %>
    </li>
<% end %>
</ul>
</div>